### ISSUE TITLE
Aditional Configuration for FBW A32NX

### ISSUE THREAD

**Issue by jcabanascachi** [RoystonS/BetterBravoLights#14]
**Software version**

0.4.2.0

**Modifying or adding?**

Modifying some of the configuration

**Which Aircrafts?**

A32NX FBW

**The configuration**

```ini
AUTOPILOT = L:A32NX_AUTOPILOT_1_ACTIVE == 1 OR L:A32NX_AUTOPILOT_2_ACTIVE == 1
LowFuelPressure = A:GENERAL ENG FUEL PRESSURE:1, psi <= 10 OR A:GENERAL ENG FUEL PRESSURE:2, psi <= 10
LowOilPressure = A:ENG OIL PRESSURE:1, psi <= 60 OR A:ENG OIL PRESSURE:2, psi <= 60
Door = A:CANOPY OPEN, percent > 0 OR A:EXIT OPEN:0, percent > 0 OR A:INTERACTIVE POINT OPEN:3, percent > 0 OR A:INTERACTIVE POINT OPEN:5, percent > 0
; StarterEngaged will turn on when engine mode selector is in IGN/START
StarterEngaged = A:TURB ENG IGNITION SWITCH EX1:1, enum == 2
APU = A:APU GENERATOR ACTIVE, bool == 1
ParkingBrake = L:A32NX_PARK_BRAKE_LEVER_POS == 1
; AntiIce will be on when PROBE/WINDOW HEAT is on, 
AntiIce = L:A32NX_MAN_PITOT_HEAT == 1
LowHydPressure = L:A32NX_HYD_BLUE_PRESSURE < 2000 OR L:A32NX_HYD_GREEN_PRESSURE < 2000 OR L:A32NX_HYD_YELLOW_PRESSURE < 2000
LowVolts = L:A32NX_ELEC_DC_1_BUS_IS_POWERED == 0 OR L:A32NX_ELEC_DC_2_BUS_IS_POWERED == 0
```

**Additional context**

Thanks for this amazing job you have done

**Comment by RoystonS** [comment]
Hi @jcabanascachi,

Yep, I did indeed completely miss your `LowHydPressure` entry - thank you!

I've:

- applied your `AUTOPILOT` entry; I've also found the corresponding LVARs for the stock A320 and added those for that. (Not the same, sadly.)
- simplified the `StarterEngaged` entry to match yours as there's only one starter.
- used your simplified APU entry (it was the same as I already had for the stock A320).
- applied your `ParkingBrake` entry as is clearly needed for the FBW A320.
- applied your `LowHydPressure` entry.

Those easy ones are in Better Bravo Lights v0.5.0 which I've just shipped.


That just leaves `LowVolts` and `AntiIce` which are a bit more complex...

*Low Volts*

Yes, I can see that checking if the electrical buses are powered is certainly of interest.  So I've checked FBW's own definition for this annunciator light.
They use `ELECTRICAL MAIN BUS VOLTAGE < 24`.  Here are the appropriate parts of their code: https://github.com/flybywiresim/a32nx/blob/d7556f04a219d83101afd74665f2a96781cd5a04/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js#L2352 and 
https://github.com/flybywiresim/a32nx/blob/d7556f04a219d83101afd74665f2a96781cd5a04/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js#L2459.
So whilst I agree that your definition is really good, and possibly more useful, because it's one of the few places where I have an actual FBW definition of that exact annunciator, I think I should probably keep *their* definition.
(But you can obviously keep your configuration exactly as you prefer - that's the point of the tool.)

*Anti Ice*

I've asked around on a couple of forums about how the AntiIce light is supposed to work but I've not had any responses.
Yes, I completely agree that you ideally want all lights _off_ when taking off.

Going by the standard Bravo configuration they went for displaying the light if pitot heat _isn't_ on.  So that's a useful default to emulate in the absence of other information.

However, looking at the annunciator configuration for the FBW A320 I can see it shows two different anunciators: "PITOT NO HT L" and "PITOT HT ON L".
Their code: https://github.com/flybywiresim/a32nx/blob/d7556f04a219d83101afd74665f2a96781cd5a04/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js#L2398-L2399
Is that a more nuanced thing which warns about both "Hey, you should have pitot on, but you don't" and "Hey, you don't need pitot on, but you have it on"?
If so, that's a much more obvious and nicer behaviour to follow: that gives you a warning that something isn't as it should be.
Looks like G1000s show 'PITOT NO HT' if the engine is on and the pitot heating isn't, and 'PITOT HT ON' if the pitot heat is on but the engine isn't.
Do you know what the behaviour is for those warning on the FBW A320?
 
By the way, for both the stock A320 and the FBW A320, the three `L:XML_MOMENTARY_PUSH_OVHD_ANTIICE_ENG1_PRESSED/ENG2_PRESSED/WING_PRESSED` variables
correspond to the standard `A:ENG ANTI ICE:1, bool`, `A:ENG ANTI ICE:2, bool` and `A:STRUCTURAL DEICE SWITCH, bool`, so you can access those without resorting to L:vars.
But whilst the stock A320 uses `A:PITOT HEAT, bool` for the pitot switch, the FBW uses `L:A32NX_MAN_PITOT_HEAT` as you've seen.

So I think I'd like to go for:
1. An AntiIce that lights up if things aren't as they should be. To that end, I'll continue to look around to see how that's defined. If I can find variables that indicates icing, that's be great for the A320. So far I've failed to actually get the FBW A320 to ice up.
2. If that's not possible, we'd have to go for a single "show a warning if the heating system is on or show a warning if the heating system is off [irrespective of whether it should be]".
In that situation I'd like to follow the Bravo default of showing that it's _off_. So I've modified the FBW configuration to be the same as that for the stock A320 but with
`A:PITOT HEAT, bool` replaced with `L:A32NX_MAN_PITOT_HEAT`.  That gives the same behaviour as with other aircraft, which is that the AntiIce light is lit if NO anti-ice buttons are on.

However, as we've discussed, some people will prefer the logic to work the other way round, so I've just added a new feature to Better Bravo Lights v0.5.0 that makes it easy to invert the behaviour of a specific light without having to completely invert all the bits of logic. You can now just write `Invert = AntiIce` and it'll invert any existing logic without needing to go in and modify the logic. (My logic here is that users of Better Bravo Lights should be needing to maintain as few custom configuration entries as possible, and to make those entries as simple as possible.)

I'm also wondering if `AntiIce = OFF` might be a better configuration for the A320... ;-)

I'm rather unhappy with all of this, so I've just put a specific question about `AntiIce` in the release notes for 0.5.0 to see if we can get some more insight.

**Comment by jcabanascachi** [comment]
Hi @RoystonS 

I checked the code of the FBW A32NX and you are right, that is their definition of Low Volts, however, if I start a flight in cold and dark mode (no electricity at all) the light LOW VOLTS is off. I think because of the batteries, after a while, the batteries start to discharge very slowly but the variable Electrical main bus voltage, volts < 24 did not change at all. Maybe I have to wait longer enough so the batteries discharge completely to see a change in the variable. I think that I will keep my configuration because I prefer to have it on and when powering the aircraft with something else but the batteries, it turns off. I like that much more :D

About the AntiIce, I think you are also correct, you should leave it as Bravo default with your new feature to invert, so everybody can adjust it as they want. I always fly with the Pitot heat on, I do not want any surprises in the air, the invert feature comes perfectly to me because my AntiIce light turns off as soon as I push the Probe/window heat button in the cockpit. I am using it now as a reminder to have it on.

I hope someone can give more insights about this, it is a great tool what you have created so far and I have been waiting for something like this for a long time, I am so enjoying it, there is a cockpit switch in the A320 that is the Test Annunciator Light that turns all the lights on in the cockpit, I have already configured the Better Bravo Lights so all the lights in the Bravo also turn on with this switch. Awesome!

I will try to get some extra info in FBW discord about the AntiIce light.

**Comment by RoystonS** [comment]
Yep, I've been very unhappy with the LVar connections for a while.  As a result I've just about finished writing my own WASM module for reading LVars which will completely remove the need for FSUIPC. (It's working; I'm just testing and tidying up.)

Should make installation much simpler and the tool much more reliable!

**Comment by jcabanascachi** [comment]
Hi!

I just tried the new version (0.6.0) with your new WASM module, it works perfectly!!

This is getting better and better!

Thank you so much!

**Comment by RoystonS** [comment]
Excellent stuff! So you're not having to do any lvar/reload shuffle any more?

**Comment by jcabanascachi** [comment]
Not any more!

I installed the latest version, made my changes in config file, run the MSFS2020 and that is all! It worked perfectly!

I had to close FSUIPC because it started with the sim but it was not connected as I configured it like that (I may uninstall it now), nothing else.

Excellent job as always!

**Comment by RoystonS** [comment]
Fabulous. That's great news!
