### ISSUE TITLE
BBL not working after update to 0.7.0

### ISSUE THREAD

**Issue by ed1111** [RoystonS/BetterBravoLights#30]
0.7.0

**Software version**

**What are you trying to do?**  After installing 0.7.0 using install batch file, Bravo lights not correct.  This is with FBW A32Nx.  Prior version was working perfectly.

**What's the problem?**  Starter Engaged light always on.  Parking Brake light always off.  Not sure other lights working correctly.

**What have you tried already?**  I tried uninstalling BBL 0.7.0 using uninstall batch file.  Reinstalled again using install batch file.  Still lights are not correct.

**Other software**
After installing BBL using batch file, is BBL supposed to show in MSFS Addons Linker?  The AFC_Bridge file still shows in MSFS Addons Linker.  Another question, if I uninstall BBL using uninstall batch file, do I need to reinstall AFC_Bridge file?

- MSFS: Windows Store on S: drive.  MSFS SU7.  FBW A32Nx Development version - latest update.

Is there a way to verify whether BBL is installed and working correctly or not?  Thank you for any help you can provide.

**Comment by RoystonS** [comment]
Hi there,

Not quite sure what's going on there. If you bring up the Debugger screen, what values are being shown for the starter engaged and parking brake expressions? (Click on the starter engaged and parking brake buttons and see what it shows.)

Do you have your own configurations for FBW or are you just using the stock configuration that comes with BBL?

Regarding installation:
* When you install BBL you should see a `better-bravo-lights-lvar-module`  in the Community folder.
* The AFC_Bridge doesn't actually need to be in the Community folder to work. I don't know why they put it in there. It's very confusing.
* When you install or uninstall BBL it'll tell you that it has 'enabled BBL and disabled AFC' or vice versa. Installing BBL doesn't delete AFC: it simply disables it. Uninstalling BBL re-enables AFC.  If it's not telling you those things during installation and uninstallation, something is wrong.

**Comment by ed1111** [comment]
OK, thanks @RoystonS .

I think I originally (with prior build of BBL) had that module showing in the Community folder, but not now.

What would the best way be to completely remove all BBL files so that I can try a new install?  I've already tried using the uninstall batch file and reinstalling (with the batch file) BBL again and that didn't seem to do it.

Is there a step-by-step guide for how to update BBL to a new version?  I thought I did it right, but maybe not.  Particularly, what to do with the old version (use uninstall batch file?).

**Comment by RoystonS** [comment]
Removing BBL is straightforward: run the uninstall script. That'll remove the module from the Community folder, and remove the entry for BBL from the MSFS startup script.

Updating BBL is also simple: just install the new version. There's absolutely no need to uninstall any old version.

I'm just giving the FBW a try right now. Took me several attempts to get MSFS to start up with it, but I'm in now, and I have a parking brake light on my Bravo that came on when I got into the flight, and it went off when I took the brake off. The 'starter engaged' light came on when I started the engine. I don't really fly the FBW so I don't know what I'm doing, but the basics seem to be working.

Very happy to give you as much help as needed to get it all going.

**Comment by RoystonS** [comment]
Here's how to find out what's going on with BBL:

Right-click the BBL icon in your system tray - the little light-bulb icon:
<img width="180" alt="image" src="https://user-images.githubusercontent.com/19773/155905825-ae3fcdd2-3e38-4076-a599-f4ab06d329e8.png">
Select the 'Debugger' option:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/19773/155905853-4c8beb4a-7b73-4acf-8c69-10154558369d.png">
That'll show the "Debugger" UI that shows the gory details of every light that BBL is managing. If I click 'Parking Brake' I see the following:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/19773/155905903-96578e67-c038-428a-8c0a-ca069004d2e6.png">

Names of lights shown in red in this display should be lit on the real physical Bravo Throttle. Names of lights shown in green (for gear lights, basically) indicate that those Bravo lights will be green rather than red (or yellow!).  So you can tell from the above screenshot that I have 'HDG', 'VS', 'LOW OIL PRESSURE', 'ANTI ICE', 'STARTER ENGAGED', 'APU' lit and three green gear lights on. And that's also exactly what I see on my actual Bravo.

Clicking on the circular radio button next to any light name (as I have done with 'PARKING BRAKE' above) will show you the 'condition' (or 'expression') that BBL uses - for that aircraft - to figure out whether to turn the light on or off.  For Parking Brake on the FBWA320, the condition is

`((A:CIRCUIT GENERAL PANEL ON, bool == 1) AND (L:A32NX_PARK_BRAKE_LEVER_POS == 1))`
These expressions can be a bit like gobbledigook if you're not used to them, but roughly, this one says that the parking brake light should be on if the general circuit panel is turned on AND the brake lever position value is `1`.  In less technical jargon it means that the brake light is on if the electrics are on AND the brake is actually on.

Underneath that display BBL shows the values of all those variables mentioned in the expression. In my case, the general circuit panel is on BUT the brake lever position value is `0`. That is, the electrics are on, but my parking brake is OFF. So my parking brake _light_ isn't on, and that's correct.

If I pop back into my A320 and pull the parking brake on, the BBL debugger display changes to:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/19773/155906068-f267453f-26fc-42d9-a424-5d9cf923d690.png">

The differences there are fairly subtle. You'll notice that 'PARKING BRAKE' is now red, indicating that the Bravo parking brake light should be on, and we can see _why_ it's now on by looking at the variables: the 'brake lever position' value is now `1` instead of `0`.


How does yours look?

**Comment by RoystonS** [comment]
Oh, one other note on _installing_ BBL. When you run the `install.cmd` script, it doesn't copy all of the BBL files somewhere else. It just runs them from wherever you unpacked the `.zip` file.

The installation script does two things:
1. It copies a module into the MSFS Community folder, needed for accessing some types of variables.
2. It modifies the MSFS startup configuration to run BBL when MSFS starts.

So if you unpack your zip, run the install from that unpacked folder, then delete that folder, BBL won't work, because you've deleted it. I'm wondering if that's what's happening to you?

**Comment by ed1111** [comment]
Royston,

I just tried to reinstall the prior version of BBL using its batch/script file.  It also is not installing at all.  Do you have any ideas why?  I really don't know what changed on my system, other than normal Windows updates and Nvidia graphics driver updates.  Could my problem have to do with updates to the Windows .NET framework?

--Ed

**Comment by RoystonS** [comment]
Hi there,
It shouldn't be related to system updates around .NET.  BBL deliberately ships with its own copy of the .NET framework (which is the _vast_ majority of its download size!)

Ok, so let's take it back step-by-step.  When you double-click on the install script, exactly what do you see? Do you get any messages or any errors?

**Comment by RoystonS** [comment]
Btw, here's what I see when I double-click `install.bat`:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/19773/156033471-4ad48956-863f-4ae9-b281-8e9162bfe636.png">

**Comment by ed1111** [comment]
Royston, I believe I have found the problem.  I was opening the install.bat file by right clicking and choosing to run it with administrative privileges.  After doing so, the cmd.exe window does not even open.

I then tried just left clicking on the install.bat file.  The cmd.exe window opened and the white small window in your post appeared.  After clicking OK, I then checked my MSFS Community folder and the module is there.  I am assuming that this indicates a proper install.  I haven't started up MSFS yet to check, but I will post again after doing so.

If this is indeed the cause, perhaps you might clarify on the BBL page's install instructions that the user should not run the insstall.bat file with administrative privileges.

**Comment by ed1111** [comment]
I just flew a short flight with the C208B.  I am very pleased to report that BBL seemed to load and work correctly.  The light bulb icon appears and the Bravo lights seem to be functioning correctly.  I must admit that I do have to further test with more flights and more complex planes, but so far so good.

Royston, thank you for all of your comments and the information you provided.  You have done the sim community a great service in creating and supporting this addon.  Much appreciated.

**Comment by RoystonS** [comment]
Fantastic. Thanks for letting me know! Yup, BBL doesn't require admin privileges.

Yup, you'll see different paths to mine, but as long as they match your installation, that's all perfectly fine. It very deliberately scans to see where you've installed MSFS, and where your Community folder is.

I might tweak the `install.bat` script itself to tell people not to run with admin privileges if they do. That way we reduce the mental load of users and aren't reliant on people reading instructions. (Few people read them!)
