### ISSUE TITLE
FBW A320 Config Issues - HDG and VS buttons stay lit

### ISSUE THREAD

**Issue by A320AutoPilot** [RoystonS/BetterBravoLights#36]
Hello,

I'm running the latest version of BBL. Version 0.7. I'm trying to program the autopilot buttons HDG through IAS to work properly on the Bravo Throttle Quadrant. The code that I'm putting into the "config" folder isn't having the effect that it should be. I've added this code:

[Aircraft.FlyByWire_A320_NEO]
HDG = A:A32NX_FCU_HDG_MANAGED_DASHES == 1
NAV = A:XMLVAR_Baro1_Mode == 1
APR = A:A32NX_FCU_APPR_MODE_ACTIVE == 1
REV = A:XMLVAR_Baro1_Mode == 2
ALT = A:AUTOPILOT ALTITUDE SLOT INDEX, bool == 2
VS = A:A32NX_AUTOPILOT_VS_SELECTED == 0
IAS = A:A32NX_FCU_SPD_MANAGED_DASHES == 1

to the bottom of the document and saved it. Nothing happens. HDG and VS lights are still stuck on, with no other lights illuminated on the autopilot panel. I've tried moving the code into the larger base config file and it makes no difference. I have the Steam version of MSFS.

Thanks!

**Comment by RoystonS** [comment]
I can see that you posted on another issue (https://github.com/RoystonS/BetterBravoLights/issues/33#issuecomment-1107617999) that you copied this block of code, but it looks like you've made some breaking changes when you copied it.

You've changed all the `L:` variables to be `A:` variables, which will completely stop them working.

**Comment by RoystonS** [comment]
When BetterBravoLights is running, right click its (light bulb) icon on the system tray and select 'Debugger'. That'll bring up the Lights Monitor window which will allow you to inspect the conditions and status of every individual light.
<img width="165" alt="image" src="https://user-images.githubusercontent.com/19773/165003758-e95896c7-a32e-4ef5-b5cf-3f1376259983.png">

That'll tell you which expressions are being used, whether they're working correctly and so on.

Full documentation for the configuration files is available here:
https://roystons.github.io/BetterBravoLights/configuration.html

**Comment by RoystonS** [comment]
To help you out, I have some questions:

* Have you got BBL working at all? You're trying to add custom configurations found somewhere else, but have you got it basically working before you do that?
* Have you installed BBL or are you running it manually?
* Which aircraft are you flying with? I'm guessing it's the FBW A320 given the extra config you're trying to add?

I can see from issue #33 that you've tried making modifications to both the user-editable Config.ini file and the .ini file that comes with BBL itself. You may have got yourself into a serious mess if you're modifying the internal .ini file and attempting to change both. I'd suggest starting with a clean copy of BBL.

(Let's just keep your questions here on this issue #36 instead of using #33 as well otherwise conversations will get confusing.)

**Comment by A320AutoPilot** [comment]
![VS](https://user-images.githubusercontent.com/104275460/165004284-ba395560-3956-42a8-bd0a-7b83f024847d.png)
![config](https://user-images.githubusercontent.com/104275460/165004285-c39af3c2-2cba-4c62-872f-f4c50e2e5f26.png)
![HDG](https://user-images.githubusercontent.com/104275460/165004286-4992895c-d853-4296-be1e-160934f799f7.png)

Sorry for the confusion on the different threads. I'll reply here from now on. Attached are picrures of my conig folder and the debugger on the HDG and the VS buttons.

**Comment by A320AutoPilot** [comment]
> 

BBL works perfectly for everything else. The only issue is the AP panel lights. I installed BBL. It runs automatically on startup. I'm flying with the FBW A320. I did make some changes to the .ini file. I'm new to this and got myself confused. All of the changes were reverted, but I can do a fresh install. Would uninstalling/reinstalling BBL do that for me? Thanks!

**Comment by RoystonS** [comment]
@A320AutoPilot Thanks - that's really helpful! I can see that BBL is working happily with MSFS so that rules a whole load of potential problems out.

Yep, I'd delete the existing copy of BBL and unpack and install a fresh one.  I've had plenty of occasions where somebody has said they've reverted changes and hasn't _quite_ managed to revert correctly. Start from fresh and we'll know for absolute sure where we're starting from!

Then add your extra config entries to the user Config.ini file, as you've previously done:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/19773/165004568-eedeb871-59b2-48e7-b7d9-2f2f762df435.png">

Once you've got MSFS and BBL up and running with that config, bring up the Lights Monitor window and select the radio button next to a light that isn't working as you want it to (as you've done with HDG in the screenshot above). That'll show you the condition expression that you've defined for that light, and show you the values of all the variables from the sim that are feeding into that condition.  That should start to give you some clue as to why the light is currently on or off, and why it isn't matching your expectations.

It might be best if we take it one light at a time. Pick one that isn't working, and let me know what you're seeing for it, and why that doesn't seem right?

**Comment by A320AutoPilot** [comment]
> 

Can't tell you how much I appreciate you taking the time to help me fix this. So a fresh install seems to have fixed the problem! The lights are working as they should. Do you have any suggestions for where I could get information on programing the FBW settings into the Bravo AP panel? The only other thing I'd like to figure out is how to program the anti ice warning on the bravo panel to come on when the anti ice is actually on. Right now the light is illuminated when the anti ice system is off.

**Comment by RoystonS** [comment]
Ah, good stuff. Glad to hear a fresh install sorted out most of the problems.

FlyByWire document their LVars here: https://github.com/flybywiresim/a32nx/blob/master/docs/a320-simvars.md
(You can use the new experimental variable list view in BBL to view and filter the values, which may help.)

Anti-Ice is a specific and _very_ interesting question that I've already asked a couple of people about: what should the 'Anti-Ice' light actually indicate?  The default configuration that comes with the out-of-the-box Bravo throttle software lights up the 'Anti-Ice' light if the (standard GA non-FBW) anti-ice system is _off_.

(I did have a bit of a conversation about that in issue #14. Never really got to the bottom of it. Suggestions very welcome.)

As a temporary measure, if you simply want to invert a light's existing logic you can use BBL's `Invert` feature (documented here: https://roystons.github.io/BetterBravoLights/configuration.html)

Just add `Invert = AntiIce` to the config for a particular aircraft and it'll invert the logic for that light.

But I'd really like to get to the bottom of when the AntiIce light should be on or off.  I'm an amateur sim pilot who doesn't fly the A320, so I need help on that.  If the A320 Anti-Ice config I'm shipping with BBL is definitely the wrong way round, I can of course swap that in the shipping software.

**Comment by A320AutoPilot** [comment]
So I'm no real-world A320 pilot but I've spent a lot of time flying the FBW A320 in the sim and in my opinion there are two options for when the anti ice should turn on. Neither really line up neatly to one single "anti ice" button, and which is correct is I suppose a matter of interpretation, but either are better than the current programming. So either the anti ice light turns on when the ice detected warning displays on the ECAM, as a reminder to turn the system on, or it turns on when the system is on, as a warning that you've left the anti ice system on. I think for the bravo throttle quadrant I'd probably want the ladder, but again that really depends on how often you watch the lights screen for warnings as opposed to reminders for things you left on. Hope that helps!

**Comment by RoystonS** [comment]
Hey @A320AutoPilot. Yup, I've just spent a few hours playing with the A320 and from the way the Anti-Ice buttons on the overhead panel work (i.e. they light up when active) and the way the messages appear on the ECAM (to warn you that you've left the AntiIce buttons on), it seems that lighting up the Bravo AntiIce light when any of the Anti-Ice systems are on seems the way to go.

(As you say, the other option would be to do something with the ice-detection warning system, e.g. to reflect a mismatch between the ice-detection warning and anti-ice system status, but that doesn't quite feel like it fits the spirit of the rest of the annunciators to me...)

I'll release a new BBL shortly with reversed AntiIce logic for the A320, so that it simply displays the light when any of the AntiIce buttons are active.

**Comment by RoystonS** [comment]
Released in v0.8.0
