### ISSUE TITLE
Conversing numeric expressions

### ISSUE THREAD

**Issue by Dimitri-dW** [RoystonS/BetterBravoLights#47]
### Software version

0.8.1

### What are you trying to do?

I'm trying to map the Door light from the Bravo to the custom L:vars of the NextGen EMB110

### What's the problem?

BBL is giving the error 'A boolean expression is needed to drive a light, not a numeric one.' Thus no light can be driven.

### What have you tried already?

(L:EMB110P1 CARGO DOOR OPEN > 0) OR (L:EMB110P1 MAIN DOOR OPEN > 0)
(L:EMB110P1 CARGO DOOR OPEN, bool > 0) OR (L:EMB110P1 MAIN DOOR OPEN, bool > 0)
L:EMB110P1 CARGO DOOR OPEN > 0 OR L:EMB110P1 MAIN DOOR OPEN > 0
L:EMB110P1 CARGO DOOR OPEN == 1 OR L:EMB110P1 MAIN DOOR OPEN == 1
(L:EMB110P1 CARGO DOOR OPEN, percent > 0) OR (L:EMB110P1 MAIN DOOR OPEN, percent > 0)

None of these work

**Comment by RoystonS** [comment]
Hi @Dimitri-dW

* Units such as `, bool` or `, percent` only work with `A:` variables, not `L:` variables, so we can rule those options out.
* I think the problem is that you seem to have an L: variable with spaces in the name. Is that definitely correct? I've never seen one of those before. `A:` variables tend to have spaces in but I've never seen an `L:` variable with spaces in its name before; they all use underscores (`_`) instead of spaces.  If they need to support spaces I'll need to change the BBL expression parser to support that.

Where did you get the name of `L:EMB110P1 CARGO DOOR OPEN` from?

**Comment by Dimitri-dW** [comment]
Just did the check, when I change the Lvars to ```L:EMB110P1_MAIN_DOOR_OPEN``` I get the response 'LVar does not exist yet; this aircraft may not support it'

**Comment by RoystonS** [comment]
Could you paste in a screenshot of BBL showing that variable name?

**Comment by Dimitri-dW** [comment]
![image](https://user-images.githubusercontent.com/75665554/170319590-c309065d-96c7-4ab2-9f4e-5e75cd26505a.jpeg)

**Comment by RoystonS** [comment]
Okey doke. I'll make a change to the parser so it supports spaces in the names. Brb.

**Comment by RoystonS** [comment]
Change done and tested. Releasing with the fix shortly.

**Comment by Dimitri-dW** [comment]
Awesome! Splendid work!

When all is done and tested at my end I'll share the profile with you. Think I'm almost happy with it; even figured out when the warning lights in the annucinator panel come on and tried to match that as close as possible on the bravo

**Comment by RoystonS** [comment]
I just shipped 0.8.2 which includes the fix for the issue you found.  Yep, would love to share another profile for everybody. It's not an aircraft I have, so it'd be very much appreciated!
